# Generated by Django 5.1.7 on 2025-03-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_films_delete_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Books',
        ),
    ]
