# Generated by Django 5.1.7 on 2025-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_films_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='укажите дата создания книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='укажите описание книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите создателя книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='укажите email'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия')], max_length=10, null=True, verbose_name='укажите жанр книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='books/', verbose_name='загрузите фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(null=True, verbose_name='укажите ценник книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите название книги'),
        ),
    ]
